### PR TITLE
fix(core): include serve target only for applications

### LINKED ISSUE #28: [BUG] Serve target should not be generated for libraries
**Describe the bug**
When generating a library, the newly-added section of `workspace.json` includes a `serve` target. This target invokes `dotnet run` under the hood, which is not supported for library projects. The `serve` target should only be added to application projects.

**To Reproduce**
1. Create a new Nx workspace
2. Generate a new class library with `npx nx generate @nx-dotnet/core:lib my-lib --template classlib --language C#`
3. Open `workspace.json` and find the section for `my-lib`.
4. The `architect` key includes a `serve` target, which will always fail when run.

**Expected behavior**
A `serve` target should not be included for library projects. Only the `build` target should be scaffolded (plus a `test` target if a test template was specified).

**Environment:**
 - OS: Windows
 - Browser: N/A
 - Version: 0.2.0
 - Affected Packages: `@nx-dotnet/core`

### PR DESCRIPTION
**Pull request by bcallaghan-et**
Do not include serve target for libraries as they cannot be run directly.

Fixes #28

### CODE REVIEW

File: packages/core/src/generators/utils/generate-project.ts [hunk 1]
```diff
@@ -188,7 +188,7 @@ export async function GenerateProject(
     sourceRoot: `${normalizedOptions.projectRoot}`,
     targets: {
       build: GetBuildExecutorConfiguration(normalizedOptions.projectRoot),
-      serve: GetServeExecutorConfig(),
+      ...(projectType === 'application' && { serve: GetServeExecutorConfig() }),
```
Comment (AgentEnder) [inline packages/core/src/generators/utils/generate-project.ts:191]: Instead of taking advantage of the fact that {...(false)} is equivalent to {}, would you care to swap this to a ternary?

`...(projectType === 'application' ? { serve: GetServeExecutorConfig() } : {})`

Its a bit clearer, and the other feels like something that could be changed in later node / ecma versions (although it probably will not be due to backwards compat.)

**Review by AgentEnder — CHANGES_REQUESTED** [review]
This looks good, and definitely works. One small suggestion, albeit a bit of a nit pick.

File: packages/core/src/generators/utils/generate-project.ts (hunk 1 above)
Comment (bcallaghan-et) [reply packages/core/src/generators/utils/generate-project.ts]: No problem. I just learned about this syntax recently, and I couldn't decide which I liked better.

Comment (AgentEnder) [reply packages/core/src/generators/utils/generate-project.ts]: Yeah, I had to look it up when I was reviewing the code. Generally if thats the case its best to avoid the syntax and be explicit. Definitely a neat little syntax though, I'll have it floating around my head for a few days before I come to a solid stance on if it is worth using.
